[package]
name = "photocopy"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1"
eframe = "0.28.1"
egui = "0.28.1"
windows ={version = "0.58.0", features = ["Win32", "Win32_Storage", "Win32_Storage_FileSystem"]}
windows-drives = "0.5.0"
